# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.2
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
  - repo: local
    hooks:
      - id: fix-header-guards
        name: fix C++ header guards
        entry: python3 scripts/fix_header_guards.py
        language: system
        files: \.(h|hpp)$
      - id: scripts-unit-tests
        name: scripts/ unit tests
        entry: pytest scripts/test/ -v
        language: python
        additional_dependencies:
          - pytest
          - PyYAML
        files: ^scripts/
        types_or: [python]
        pass_filenames: false
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.26.1
    hooks:
      - id: gersemi
  - repo: https://github.com/google/go-jsonnet
    rev: v0.22.0
    hooks:
      - id: jsonnet-format
      - id: jsonnet-lint
        # The files in test/max-parallelism import files that are generated during the build.
        # We therefore exclude them from linting, but still format them.
        exclude: ^test/max-parallelism
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        types_or: [yaml]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.0
    hooks:
      - id: markdownlint-cli2
        args: [--fix]
