name: 'Handle Fix Commit'
description: 'Commits changes if possible, otherwise creates a patch and comments on the PR.'

outputs:
  changes:
    description: 'Whether changes were detected'
    value: ${{ steps.check_changes.outputs.changes }}
  pushed:
    description: 'Whether changes were pushed'
    value: ${{ steps.commit_and_push.outputs.pushed }}
  commit_sha:
    description: 'The full SHA of the pushed commit'
    value: ${{ steps.commit_and_push.outputs.commit_sha }}
  commit_sha_short:
    description: 'The short SHA of the pushed commit'
    value: ${{ steps.commit_and_push.outputs.commit_sha_short }}
  patch_name:
    description: 'The name of the patch file if created'
    value: ${{ steps.create_patch.outputs.patch_name }}

inputs:
  tool:
    description: 'The tool name reported in commit messages and PR comments.'
    required: true
  working-directory:
    description: 'The working directory for git operations.'
    required: false
    default: 'phlex-src'
  token:
    description: 'The PAT to use for committing.'
    required: true
  pr-info-ref:
    description: 'The ref (branch name) of the PR'
    required: true
  pr-info-repo:
    description: 'The repository of the PR'
    required: true
  retry-attempts:
    description: 'The number of times to retry pushing the commit.'
    required: false
    default: '6'

runs:
  using: "composite"
  steps:
    - name: Check for changes
      id: check_changes
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> "$GITHUB_OUTPUT"
        else
          echo "changes=false" >> "$GITHUB_OUTPUT"
        fi

    - name: No changes to apply
      if: steps.check_changes.outputs.changes == 'false' && github.event.pull_request.number
      uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
      with:
        message: 'No automatic ${{ inputs.tool }} fixes were necessary.'

    - name: Get PR maintainer_can_modify property
      id: pr-properties
      if: steps.check_changes.outputs.changes == 'true' && github.event.pull_request.number
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          core.setOutput('maintainer_can_modify', pr.maintainer_can_modify);
    - name: Commit fixes
      if: steps.check_changes.outputs.changes == 'true' && (inputs.pr-info-repo == github.repository || steps.pr-properties.outputs.maintainer_can_modify == 'true')
      id: commit_and_push
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        TOOL: ${{ inputs.tool }}
        TOKEN: ${{ inputs.token }}
        PR_REF: ${{ inputs.pr-info-ref }}
        RETRY_ATTEMPTS: ${{ inputs.retry-attempts }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

        trap 'rm -f ~/.git-credentials' EXIT
        rm -f ~/.git-credentials
        umask 077
        cat <<EOF > ~/.git-credentials
        https://x-access-token:$TOKEN@github.com
        EOF
        git config --local credential.helper 'store --file ~/.git-credentials'

        git add -u
        git commit -m "Apply $TOOL fixes"

        for i in $(seq 1 "$RETRY_ATTEMPTS"); do
          if git push origin HEAD:"$PR_REF"; then
            echo "Push successful on attempt $i."
            COMMIT_SHA=$(git rev-parse HEAD)
            COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)
            echo "commit_sha=$COMMIT_SHA" >> "$GITHUB_OUTPUT"
            echo "commit_sha_short=$COMMIT_SHA_SHORT" >> "$GITHUB_OUTPUT"
            echo "pushed=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          if [ "$i" -eq "$RETRY_ATTEMPTS" ]; then
            break
          fi
          echo "Push failed on attempt $i. Fetching and rebasing before retry..."
          git fetch origin
          if ! git rebase origin/"$PR_REF"; then
            echo "::error::Automatic rebase failed. Please resolve conflicts manually."
            exit 1
          fi
          echo "Waiting before retry..."
          sleep $((5 * i))
        done
        echo "::error::Failed to push changes after multiple retries."
        exit 1

    - name: Notify of commit
      if: steps.commit_and_push.conclusion == 'success' && steps.commit_and_push.outputs.pushed == 'true' && github.event.pull_request.number
      uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
      with:
        message: |
          Automatic ${{ inputs.tool }} fixes pushed (commit ${{ steps.commit_and_push.outputs.commit_sha_short || steps.commit_and_push.outputs.commit_sha }}).
          ⚠️ **Note:** Some issues may require manual review and fixing.

    - name: Create patch
      if: steps.check_changes.outputs.changes == 'true' && inputs.pr-info-repo != github.repository && steps.pr-properties.outputs.maintainer_can_modify != 'true'
      id: create_patch
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        git diff > fix.patch
        echo "patch_name=fix.patch" >> "$GITHUB_OUTPUT"

    - name: Upload patch
      if: steps.create_patch.outputs.patch_name
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: fix-patch
        path: ${{ inputs.working-directory }}/${{ steps.create_patch.outputs.patch_name }}

    - name: Comment with patch instructions
      if: steps.create_patch.outputs.patch_name && github.event.pull_request.number
      uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
      with:
        message: |
          Automatic fixes are available but could not be applied directly because this PR is from a fork and "Allow edits from maintainers" is not enabled.
          Please apply the patch below to fix the issues:
          1. **Download the patch file:** You can download the patch from the "Artifacts" section of this workflow run.
          2. **Apply the patch:**
             ```bash
             git apply <path/to/downloaded/fix.patch>
             ```
          3. **Commit the changes:**
             ```bash
             git commit -am "Apply ${{ inputs.tool }} fixes"
             ```
